spring:
  security:
    oauth2:
      client:
        registration:
          github:
              clientId: clientId
              clientSecret: secret
          google:
              client-id: clientid
              client-secret: secret
 
# ...
          